ABC Fashion Co PRoject/force-app/main/default/objects/Account/fields/Customer_Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Customer_Date_Of_Birth__c</fullName>
    <description>Customer Date Of Birth</description>
    <label>Customer Date Of Birth</label>
    <type>Date</type>
</CustomField>

ABC Fashion Co PRoject/force-app/main/default/objects/Account/fields/Loyalty_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Loyalty Customer ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ABC Fashion Co PRoject/force-app/main/default/objects/Account/fields/Profile_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Profile_Access_Token__c</fullName>
    <description>Unique token for customer profile access</description>
    <label>Profile Access Token</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ABC Fashion Co PRoject/force-app/main/default/objects/Account/fields/Shoe_size__c.field-meta.xml
<CustomField>
    <fullName>Shoe_size__c</fullName>
    <label>Shoe size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6.0</fullName>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7.0</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8.0</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9.0</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10.0</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11.0</fullName>
            </value>
            <value>
                <fullName>11.5</fullName>
            </value>
            <value>
                <fullName>12.0</fullName>
            </value>
            <value>
                <fullName>12.5</fullName>
            </value>
            <value>
                <fullName>13.0</fullName>
            </value>
            <value>
                <fullName>13.5</fullName>
            </value>
            <value>
                <fullName>14.0</fullName>
            </value>
            <value>
                <fullName>14.5</fullName>
            </value>
            <value>
                <fullName>15.0</fullName>
            </value>
            <value>
                <fullName>15.5</fullName>
            </value>
            <value>
                <fullName>16.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ABC Fashion Co PRoject/force-app/main/default/objects/Account/fields/T_shirt_size__c.field-meta.xml
<CustomField>
    <fullName>T_shirt_size__c</fullName>
    <label>T-shirt size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XS</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ABC Fashion Co PRoject/force-app/main/default/classes/CustomerProfileTestClass.cls
@IsTest
public class CustomerProfileTestClass {
    
    // Utility method to create test Account
    public static Account createTestPersonAccount(String email) {
        
        Account acc = new Account(
            FirstName = 'TestFirst',
            LastName = 'TestLast',
            PersonEmail = email,
            Phone = '1234567890',
            T_shirt_size__c = 'M',
            Shoe_size__c = '10.0',
            Customer_Date_Of_Birth__c = Date.today() - 1000
        );
        Insert acc;
        
        Account accountToUse = [SELECT FirstName, LastName, Phone, PersonEmail, Profile_Access_Token__c, T_shirt_size__c, Shoe_size__c FROM Account WHERE Id = :acc.Id LIMIT 1];
        system.debug('0.acc.===>'+JSON.serialize(acc));
        system.debug('0.accountToUse.===>'+JSON.serialize(accountToUse));
        return acc;
    }
    
    
    // Test the SendCustomerProfileLink trigger
    @IsTest
    static void testSendCustomerProfileLink() {
        
        Account testAccount = createTestPersonAccount('testemail@example.com');
        
        system.debug('0.testAccount.===>'+JSON.serialize(testAccount));
        testAccount = [SELECT Profile_Access_Token__c FROM Account WHERE Id = :testAccount.Id];
        system.debug('=====testAccount.Profile_Access_Token__c===>'+testAccount.Profile_Access_Token__c);
        Account retrievedAccount = GuestPersonAccountController.getPersonAccount(testAccount.Profile_Access_Token__c);
        system.debug('=====retrievedAccount===>'+JSON.serialize(retrievedAccount));
        
        
        List<AsyncApexJob> jobs = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE JobType = 'Queueable' AND Status = 'Completed'];
        List<Account> updatedAccounts = [SELECT Loyalty_Customer_ID__c FROM Account WHERE Id = :testAccount.Id];
        
    }
    
    // Test SendProfileLinkJob Queueable
    @IsTest
    static void testSendProfileLinkJob() {
        Account testAccount = createTestPersonAccount('testemail@example.com');
        SendProfileLinkJob job = new SendProfileLinkJob(new List<Account>{testAccount});
        Test.startTest();
        Test.stopTest();
    }
    
    // Test the CustomerProfileEmailService
    @IsTest
    static void testCustomerProfileEmailService() {
        Account testAccount = createTestPersonAccount('testemail@example.com');
        CustomerProfileEmailService.sendCustomerProfileEmail('testemail@example.com', 'TestFirst', testAccount.Profile_Access_Token__c, 'https://abc-fashion-dev-ed.develop.my.site.com/abcfashionguestcustomer');
        
    }
    
    @IsTest
    static void testUpdatePersonAccount() {
        Account testAccount = createTestPersonAccount('testemail@example.com');
        Account updatedAccount = new Account(
            Id = testAccount.Id,
            FirstName = 'UpdatedFirst',
            LastName = 'UpdatedLast',
            Phone = '9876543210',
            PersonEmail = 'updatedemail@example.com',
            T_shirt_size__c = 'L',
            Shoe_size__c = '11.0',
            Customer_Date_Of_Birth__c = Date.today() - 900
        );
        
        GuestPersonAccountController.updatePersonAccount(updatedAccount);
        
        Account updatedFromDB = [SELECT FirstName, LastName, Phone, PersonEmail, T_shirt_size__c, Shoe_size__c FROM Account WHERE Id = :testAccount.Id];
        
    }
    
    @IsTest
    static void testSendLoyaltyInformation() {
        Account testAccount = createTestPersonAccount('testemail@example.com');
        List<Id> accountIds = new List<Id>{testAccount.Id};
        
        Test.startTest();
        
        // Use the mock class defined separately
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseLoyalty());

        GuestPersonAccountController.sendLoyaltyInformation(accountIds);
        
        Test.stopTest();
        
        Account updatedAccount = [SELECT Loyalty_Customer_ID__c FROM Account WHERE Id = :testAccount.Id];
        System.assertEquals('123456', updatedAccount.Loyalty_Customer_ID__c, 'The Loyalty Customer ID should be updated.');
    }


}